### ISSUE TITLE
Build sometime don't get triggered when started from the openshift console

### ISSUE THREAD

**Issue by chmouel** [fabric8io/jenkins-sync-plugin#37]
Getting this errors when doing a start-build from openshift cli/console :

```
Jul 16, 2018 11:24:56 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher eventReceived
WARNING: Caught: java.lang.IllegalArgumentException: nodejs already exists
java.lang.IllegalArgumentException: nodejs already exists
	at hudson.model.Items.verifyItemDoesNotAlreadyExist(Items.java:640)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:264)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3812)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:337)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:259)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:259)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.modifyJob(BuildConfigWatcher.java:380)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:249)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:93)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 16, 2018 11:24:56 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher eventReceived
WARNING: Caught: java.lang.IllegalArgumentException: nodejs already exists
java.lang.IllegalArgumentException: nodejs already exists
	at hudson.model.Items.verifyItemDoesNotAlreadyExist(Items.java:640)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:264)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3812)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:337)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:259)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:259)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.modifyJob(BuildConfigWatcher.java:380)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:249)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:93)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jul 16, 2018 11:24:56 AM io.fabric8.jenkins.openshiftsync.BuildConfigWatcher eventReceived
WARNING: Caught: java.lang.IllegalArgumentException: nodejs already exists
java.lang.IllegalArgumentException: nodejs already exists
	at hudson.model.Items.verifyItemDoesNotAlreadyExist(Items.java:640)
	at hudson.model.ItemGroupMixIn.createProjectFromXML(ItemGroupMixIn.java:264)
	at jenkins.model.Jenkins.createProjectFromXML(Jenkins.java:3812)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:337)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher$2.call(BuildConfigWatcher.java:259)
	at hudson.security.ACL.impersonate(ACL.java:260)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.upsertJob(BuildConfigWatcher.java:259)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.modifyJob(BuildConfigWatcher.java:380)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:249)
	at io.fabric8.jenkins.openshiftsync.BuildConfigWatcher.eventReceived(BuildConfigWatcher.java:93)
	at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:227)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:310)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:265)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:204)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by chmouel** [comment]
BuildConfig https://hastebin.com/ulokoredid

**Comment by hrishin** [comment]
@chmouel, as mentioned earlier if build name differs from github repo name thing, won't work. #28
